apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      restartPolicy: Always
      containers:
      - env:
        - name: EXAMPLE_VARIABLE
          value: Example Value
        image: yayughregistry.azurecr.io/example:0cdfd34
        name: example
        resources:
          requests:
            cpu: 250m
            memory: 250Mi
          limits:
            cpu: 500m
            memory: 500Mi
        ports:
        - containerPort: 80
        volumeMounts:
          - name: azure
            mountPath: /wwwroot
      imagePullSecrets:
        - name: registry-secret
      volumes:
      - name: azure
        azureFile:
          secretName: azure-secret
          shareName: yayughshare
          readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: example
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.240.0.5
  ports:
  - port: 80
  selector:
    app: example
