name: Automation Script

on: [push]

jobs:
  pipeline:
    name: Pipeline
    runs-on: ubuntu-20.04
    env:
      DOCKERHUB_USER: ${{ github.actor }}
    steps:
      - name: Initiating
        uses: actions/checkout@v1
      - name: Building
        run: |
          cd iot-edge-containerized
          docker build -t azure-iot-edge -f amd64.Dockerfile .
          docker tag azure-iot-edge $DOCKERHUB_USER/azure-iot-edge:GITHUB_SHA
          docker tag azure-iot-edge $DOCKERHUB_USER/azure-iot-edge:latest
      - name: Publishing
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo $DOCKERHUB_TOKEN | docker login --username $DOCKERHUB_USER --password-stdin
          docker push $DOCKERHUB_USER/azure-iot-edge:GITHUB_SHA
          docker push $DOCKERHUB_USER/azure-iot-edge:latest
